spring.application.name=symptomchecker
//spring.datasource.url=jdbc:mysql://localhost:3301/symptomchecker_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
//spring.datasource.username=root
//spring.datasource.password=Nowmaan@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

app.jwt.secret=symptomCheckerSecretKey2024SymptomCheckerSecretKey2024SymptomCheckerSecretKey

app.jwt.expiration-ms=86400000

//postgresql://nowmaan:5qJ11D9BBacbTpZKwf6P4MH3xM8MBlTa@dpg-d6qiuafpm1nc73b43lu0-a.oregon-postgres.render.com/anurag_b4v9
spring.datasource.url=jdbc:postgresql://dpg-d6qiuafpm1nc73b43lu0-a.oregon-postgres.render.com:5432/anurag_b4v9
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=nowmaan
spring.datasource.password=5qJ11D9BBacbTpZKwf6P4MH3xM8MBlTa

